### ISSUE TITLE
[Minro] reference - duplicated entry

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#100] opened 2023-06-08 11:29 UTC
**Describe the bug**
When I entered a reference information in the Smaple (protein) - Non commercial origin,
the PMID was duplicated automatically.

**Page**
Smaple (protein) -> Non commercial origin  -> Reference  

**To Reproduce**
1. Go to 'Add Sample'
2. Select on 'Protein'
3. Scroll down to 'Non-commercial'

![Sample_Preparation_automaticallyTwiceEntered](https://github.com/glygener/glygen-array-frontend/assets/67378697/9deb46c3-31dd-449a-b7df-fa99af86f922)

**Comment by senaarpinar** [comment] 2023-07-05 15:48
this is a duplicate of #49

**Closed by senaarpinar** 2023-07-05 15:48 UTC
Labels: bug
