### ISSUE TITLE
Issues retrieving Glycans from GlyTouCan ID and adding them to Glycan list

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#87] opened 2023-06-01 15:56 UTC
If I understand this right there are two problems to solve:

1. When retrieving (at least this ID) the GlycoCT can not be converted to WURCS. What is the reason? Based on the image the structure should be straight forward.

2. When using WURCS + ID the process fails because the retrieval of ID based on WURCS is not working.

**Comment by senaarpinar** [comment] 2023-06-01 16:03
I am thinking about that too but we are getting it from glytoucan and setting the string to that field and the field is not editable. @ReneRanzinger have you looked at the code where it fails, am I right that it could not locate "R" properly?

**Comment by senaarpinar** [comment] 2023-06-01 20:40
Exception trace from the log:

org.eurocarbdb.MolecularFramework.io.SugarImporterException: null
org.eurocarbdb.MolecularFramework.io.GlycoCT.SugarImporterGlycoCTCondensed.residue_block(SugarImporterGlycoCTCondensed.java:1006)
org.eurocarbdb.MolecularFramework.io.GlycoCT.SugarImporterGlycoCTCondensed.start(SugarImporterGlycoCTCondensed.java:98)
org.eurocarbdb.MolecularFramework.io.SugarImporterText.parse(SugarImporterText.java:311)
org.glycoinfo.WURCSFramework.io.GlycoCT.WURCSExporterGlycoCT.start(WURCSExporterGlycoCT.java:77)

**Comment by senaarpinar** [comment] 2023-06-02 18:03
Item 2 is fixed. Glytoucan API is now working.

**Comment by senaarpinar** [comment] 2023-06-06 15:51
Yukie could not reproduce the first issue. Added more information to the log file in case this happens again. Closing this ticket for now.

**Closed as completed by senaarpinar** 2023-06-06 15:51 UTC
Labels: bug
