### ISSUE TITLE
Block layout : no glycan image displayed

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#103] opened 2023-06-08 10:01 UTC
**Describe the bug**
When I viewed a spot (after clicking the 'edit' button), the glycan image was not displayed.

**Page**
Block layout 'Edit' view

**To Reproduce**
1. Go to 'Block layout'
2. Click on 'edit' of one of the saved block layout
3. Select a spot
4. No glycan view in the side mini-window

**Expected behavior**
Glycan structure to be displayed (?)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 102.11.0esr (64-bit)

**Additional context**
![NoImage_screenshot](https://github.com/glygener/glygen-array-frontend/assets/67378697/53f2acb5-42a3-4429-a295-5799db4090aa)

**Comment by senaarpinar** [comment] 2023-07-03 18:42
I could not reproduce this error. When I edit a block layout (imperial user - Set1), it shows all the images. @yukie-a can you tell me which block layout in which account you were editing when this happened. If it is not data related, I need to test it on Windows/Firefox to see if it is browser related issue.

**Comment by yukie-a** [comment] 2023-07-04 11:22
Thank you for chekcing. 

I'm using 'glycoscienceslab@gmail.com' account now. There is a block layout named "Fungal, bacterial and Plant PS Array Set 2". And the sequence defined glycans are allocated in the row 16 (the last row). 

If you would need the password of this account, please let me know! 

![BlockLayout_GlycanNoImage](https://github.com/glygener/glygen-array-backend/assets/67378697/5615082c-8b60-4e74-9afc-8db064294a03)


For your information, I'm using:
Firefox 102.11.0
Windows 10 Enterprise (64-bit)

**Comment by senaarpinar** [comment] 2023-07-05 15:24
Yes, I would need the username/password for the account to be able to see
the issue.

**Comment by senaarpinar** [comment] 2023-07-21 16:45
I could not edit the layout @yukie-a has created (somehow it is messed up; features are deleted) but found the root cause of the issue. The display of images were not working for glycopeptides/glycolipids etc. Should be fixed now

**Closed by senaarpinar** 2023-07-21 16:45 UTC
Labels: bug
