### ISSUE TITLE
[BUG] Not able to add reference in the Sample (protein) metadata after deleting one item

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#101] opened 2023-06-08 11:34 UTC
**Describe the bug**
This is related to the previous issue (#100 ).
After deleting one of the reference, I tried to add another reference inforamtion. 
Howevre I recieved an error message saying "Enter all mandatory fields".

**Page**
The same page with glygener/glygen-array-backend#100 
Sample (protein) - Non commercial

![NotAbleToAddReference](https://github.com/glygener/glygen-array-frontend/assets/67378697/967c2c28-30db-4cfe-a467-cf17e00a4b11)

**Comment by senaarpinar** [comment] 2023-07-05 15:47
this is a duplicate of #49

**Closed by senaarpinar** 2023-07-05 15:47 UTC
Labels: bug
